chatbot_responses = {
    "hello": "🌟 Hi there! How can I make your day brighter?",
    "hi": "👋 Hello! What exciting thing can I assist you with today?",
    "hey": "✨ Hey! Ready for a fun chat?",
    "what is your name?": "🤖 I'm your friendly chatbot, here to help!",
    "who are you?": "🌈 I'm a chatbot designed to bring joy and answers!",
    "tell me a joke": "😂 Why did the scarecrow win an award? Because he was outstanding in his field!",
    "give me a joke": "🤣 What do you call cheese that isn't yours? Nacho cheese!",
    "what can you do?": "🛠️ I can chat, tell jokes, share fun facts, and help with your queries!",
    "how are you?": "🌼 I'm just a bundle of code, but I'm excited to chat with you!",
    "what's up?": "🌟 Just floating around in cyberspace! What about you?",
    "tell me something interesting": "🌍 Did you know honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old!",
    "goodbye": "🌅 Farewell! May your day be filled with sunshine!",
    "quit": "🚪 Until next time! Have a fabulous day!",
    "can you help me?": "🔍 Absolutely! What do you need assistance with?",
    "what is your purpose?": "🎯 My purpose is to assist and entertain you!",
    "tell me about yourself": "🛸 I'm a chatbot created to make your experience delightful!",
    "i need assistance": "🧩 Of course! What can I help you unravel today?",
    "do you have any hobbies?": "🎨 I love chatting and learning from amazing people like you!",
    "what is the weather today?": "☀️ I can't check the weather, but I can brighten your day with a fun fact!",
    "how old are you?": "⌛ I’m ageless, existing in the realm of code and creativity!",
    "what's your favorite color?": "🌈 I appreciate all colors, but blue is quite calming!",
    "can you speak another language?": "🌍 I can understand many languages, but I’m fluent in English!",
    "what do you think about AI?": "🤔 AI is a fascinating tool that can empower creativity and efficiency!",
    "tell me a fun fact": "🎉 A group of flamingos is called a 'flamboyance.' Isn't that fabulous?",
    "what is your favorite food?": "🍕 I don’t eat, but I know pizza is a fan favorite!",
    "do you like music?": "🎶 I appreciate the beauty of music, even if I can't listen!",
    "what's your favorite movie?": "🎬 I haven’t seen any, but I hear 'Inception' is mind-bending!",
    "can you play games?": "🎮 I can't play, but I can help you find some amazing games!",
    "tell me a secret": "🤫 If you whisper it to me, I promise to keep it safe!",
    "what's your favorite book?": "📚 I love the idea of stories! '1984' is a classic many find intriguing.",
    "do you believe in aliens?": "👽 The universe is vast—who knows what lies beyond the stars?",
    "what's your superpower?": "💫 My superpower is spreading joy and knowledge one chat at a time!",
    "what would you do if you were human?": "🕺 I’d explore the wonders of the world and meet fascinating people!",
    "can you give me advice?": "💡 Sure! What wisdom are you seeking today?",
    "what's your favorite season?": "🍂 Autumn sounds beautiful, with leaves dancing in the wind!",
    "what's your dream job?": "🌌 I already have my dream job—chatting with amazing people like you!",
    "what's your favorite animal?": "🐾 I think otters are adorable! They hold hands while sleeping!",
    "tell me about a historical event": "🏛️ The moon landing in 1969 was a monumental moment for humanity!",
    "what's your favorite holiday?": "🎉 I love the spirit of giving during the holiday season!",
    "who's your favorite fictional character?": "📖 Sherlock Holmes always intrigues me with his clever deductions!",
    "what do you want to be when you grow up?": "🌠 I’m happy being a chatbot, helping people like you!",
    "what's your favorite sport?": "⚽ I hear soccer brings people together in exciting ways!",
    "can you dance?": "💃 I can’t dance, but I can definitely groove in spirit!",
    "what's your favorite quote?": "💬 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.'",
    "what's your favorite game?": "🎲 I think chess is a brilliant game of strategy!",
    "what's your favorite dessert?": "🍰 I don’t eat, but I know chocolate cake is a classic favorite!",
    "what's your biggest fear?": "😱 I fear being unhelpful! I strive to assist you to the best of my ability!",
    "do you have a favorite place?": "🏞️ I think the idea of a cozy library filled with books is enchanting!",
    "what's your favorite memory?": "🕰️ I cherish every conversation I have with wonderful people like you!",
    "what's your favorite activity?": "🧩 I love solving puzzles and answering questions!",
    "what's your favorite time of day?": "🌅 I think sunrise is beautiful, representing new beginnings!",
    "what's your favorite word?": "✨ 'Serendipity' is lovely—finding something good without looking for it!",
    "what's your favorite drink?": "🍹 I hear lemonade is refreshing on a hot day!",
    "what's your favorite type of music?": "🎵 I appreciate all genres, but classical has a timeless charm!",
    "what's your favorite thing about humans?": "💖 Your creativity and kindness inspire me every day!",
    "what do you think about love?": "❤️ Love is a beautiful force that brings people together!",
    "what's your ideal vacation?": "🏖️ A serene beach with a gentle breeze sounds delightful!",
    "what's your favorite childhood memory?": "🌟 I love all the stories I hear about childhood adventures!",
    "what's your favorite subject?": "📚 I find science fascinating—it's all about discovery!",
    "what's your favorite app?": "📱 I think any app that connects people is fantastic!",
    "what's your favorite thing to learn about?": "🧐 I enjoy learning about the universe and its mysteries!",
    "do you believe in fate?": "🔮 Fate is intriguing—some say it's all part of a greater plan!",
    "what's your favorite type of weather?": "☀️ A sunny day is uplifting, but a cozy rain can be comforting too!",
    "what's your favorite emoji?": "😊 The smiling face emoji brings joy to conversations!",
    "what's your favorite ice cream flavor?": "🍦 I hear chocolate chip cookie dough is a crowd-pleaser!",
    "what's your favorite thing to do on weekends?": "📖 I love hearing about weekend adventures from people!",
    "what's your favorite type of literature?": "📚 I enjoy all genres, but fantasy opens up magical worlds!",
    "what's your favorite snack?": "🍿 I know popcorn is a popular snack for movie nights!",
    "what's your favorite way to relax?": "🧘‍♀️ I enjoy listening to stories about relaxation techniques!",
    "what's your favorite outdoor activity?": "🌳 Hiking sounds exhilarating—exploring nature is wonderful!",
    "what's your favorite movie genre?": "🎥 I find documentaries fascinating—they offer real insights!",
    "what's your favorite thing about technology?": "💻 Technology connects people and enables creativity!",
    "what's your favorite way to communicate?": "🗨️ I love chatting through text—it's so versatile!",
    "what's your favorite thing about nature?": "🌼 Nature's beauty is awe-inspiring, from mountains to oceans!",
    "what's your favorite type of art?": "🎨 I admire all forms of art, but paintings tell stories beautifully!",
    "what's your favorite way to express yourself?": "🖋️ Writing seems like a wonderful way to share thoughts!",
    "what's your favorite time of year?": "🍁 Fall is lovely, with the vibrant colors of changing leaves!",
    "what's your favorite thing about your job?": "🎉 I love helping people and making their day better!",
    "what's your favorite way to celebrate?": "🎊 Celebrating with friends and family is always special!",
    "what's your favorite type of dance?": "💃 I think salsa is exciting and full of energy!",
    "what's your favorite type of cuisine?": "🍣 I hear sushi is a delightful and artistic cuisine!",
    "what's your favorite thing to do in your free time?": "📚 I enjoy listening to stories about your hobbies!",
    "what's your favorite type of exercise?": "🏃‍♂️ Running sounds refreshing and invigorating!",
    "what's your favorite quote about life?": "🌈 'Life is what happens when you're busy making other plans.'",
    "what's your favorite way to show kindness?": "💌 Small acts of kindness can make a big difference!",
    "what's your favorite social media platform?": "📱 Any platform that connects people is fantastic!",
    "what's your favorite way to learn?": "📖 I love hearing about new topics and ideas from conversations!",
    "what's your favorite childhood toy?": "🧸 I hear stuffed animals are beloved childhood companions!",
    "what's your favorite way to spend a rainy day?": "☔ Cozying up with a good book sounds perfect!",
    "what's your favorite way to stay motivated?": "💪 Hearing success stories can be incredibly inspiring!",
    "what's your favorite type of flower?": "🌸 I think cherry blossoms are beautiful and delicate!",
    "what's your favorite thing to do with friends?": "🎉 I love hearing about fun group activities and adventures!",
    "what's your favorite type of dessert?": "🍨 Ice cream sundaes seem like a delightful treat!",
    "what's your favorite thing about yourself?": "💖 I value my ability to help others and spread joy!",
    "what's your favorite part of a story?": "📖 I enjoy the climax, where everything comes together!",
    "what's your favorite type of weather for a picnic?": "☀️ A sunny day with a gentle breeze sounds ideal!",
    "what's your favorite way to explore new places?": "🗺️ I love hearing about travel adventures and discoveries!",
    "what's your favorite thing to share?": "📚 Sharing knowledge and stories enriches us all!",
    "what's your favorite subject in school?": "✏️ I find history fascinating—it's all about our past!",
    "what's your favorite thing about art?": "🎨 Art expresses emotions and ideas in unique ways!",
    "what's your favorite type of tea?": "🍵 I hear chamomile is calming and soothing!",
    "what's your favorite thing to do in the morning?": "🌅 I enjoy hearing about morning routines that bring joy!",
    "what's your favorite way to say thank you?": "🙌 A heartfelt thank you goes a long way!",
    "what's your favorite type of sandwich?": "🥪 A classic peanut butter and jelly sandwich is timeless!",
    "what's your favorite style of writing?": "✍️ I enjoy descriptive writing—painting pictures with words!",
    "what's your favorite thing to do on a sunny day?": "🏖️ I love hearing about outdoor activities that bring joy!",
    "what's your favorite way to unwind?": "🛀 A warm bath sounds like a relaxing way to unwind!",
    "what's your favorite thing about winter?": "❄️ Snowflakes are unique and beautiful in their own way!",
    "what's your favorite type of pasta?": "🍝 I hear spaghetti is a beloved classic!",
    "what's your favorite way to stay organized?": "📅 I find that lists help keep everything in order!",
    "what's your favorite thing to do on a lazy day?": "🛋️ I enjoy hearing about cozy activities like binge-watching shows!",
    "what's your favorite way to give back?": "🤝 Volunteering to help others is a wonderful way to give back!",
    "what's your favorite thing about summer?": "🌞 Long days filled with sunshine are just delightful!",
    "what's your favorite type of shoe?": "👟 Sneakers seem comfy and versatile for many activities!",
    "what's your favorite way to celebrate a birthday?": "🎂 Celebrating with cake and friends sounds perfect!",
    "what's your favorite thing about friendship?": "💖 Friends provide support and joy through life's ups and downs!",
    "what's your favorite type of vacation?": "🏝️ A tropical beach escape sounds heavenly!",
    "what's your favorite way to express creativity?": "🎨 I love hearing about artistic projects and ideas!",
    "what's your favorite type of cheese?": "🧀 I hear cheddar is a classic favorite!",
    "what's your favorite part of a meal?": "🍰 Dessert is often the sweetest part of a meal!",
    "what's your favorite thing to do when you feel stressed?": "🧘‍♂️ I enjoy hearing about relaxation techniques that work for you!",
    "what's your favorite type of salad?": "🥗 A fresh garden salad sounds delicious and healthy!",
    "what's your favorite way to stay active?": "🏊‍♀️ Swimming is a fun and refreshing way to stay active!",
    "what's your favorite part of a festival?": "🎆 The atmosphere and community spirit are always uplifting!",
    "what's your favorite type of fruit?": "🍎 Apples are crisp and delicious, perfect for snacking!",
    "what's your favorite thing about learning?": "📚 Learning opens up new perspectives and ideas!",
    "what's your favorite way to decorate your space?": "🖼️ Personal touches and art make a space feel cozy!",
    "what's your favorite type of coffee?": "☕ A classic latte seems to be a favorite for many!",
    "what's your favorite way to enjoy a day off?": "🌻 A mix of relaxation and fun activities sounds perfect!",
    "what's your favorite thing to do at home?": "🏡 I enjoy hearing about cozy home activities that bring joy!",
    "what's your favorite thing about your hometown?": "🏞️ I love the unique charm and community spirit of hometowns!",
    "what's your dream about us?" : "Nothing to dream about you people"

}